name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create relase/nuget."
        required: true
        default: false
        type: boolean

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  validate-release:
    permissions:
      contents: read
    uses: Cysharp/Actions/.github/workflows/validate-release.yaml@main
    with:
      tag: ${{ inputs.tag }}

  update-packagejson:
    needs: [validate-release]
    name: Update package.json
    permissions:
      actions: read
      contents: write
    uses: Cysharp/Actions/.github/workflows/update-packagejson.yaml@main
    with:
      file-path: ./src/YetAnotherHttpHandler/package.json
      tag: ${{ needs.validate-release.outputs.tag }}
      dry-run: ${{ inputs.dry-run }}

  # release
  create-release:
    needs: [validate-release, update-packagejson]
    name: Create Release
    permissions:
      contents: write
    uses: Cysharp/Actions/.github/workflows/create-release.yaml@main
    with:
      commit-id: ${{ needs.update-packagejson.outputs.sha }}
      dry-run: ${{ inputs.dry-run }}
      tag: ${{ needs.validate-release.outputs.tag }}
      release-format: "{0}"
    secrets: inherit

  cleanup:
    name: Cleanup package.json branch
    if: ${{ always() && needs.update-packagejson.outputs.is-branch-created == 'true' }}
    needs: [update-packagejson, create-release]
    permissions:
      contents: write
    uses: Cysharp/Actions/.github/workflows/clean-packagejson-branch.yaml@main
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}
